# resources/player-hud/resource.toml
type = 'js'
client-main = 'client/index.js'
client-files = [
    'html/hud.html', # Dosya adını hud olarak değiştirdik
    'html/hud.css',
    'html/hud.js'
]
deps = []